### PR TITLE
Enable Hiera 5

### PR DESCRIPTION
**Pull request by reidmv**
This commit enables the control repo to use Hiera 5 environment-level
hiera hierarchy. This means adding a hiera.yaml to the repo, and moving
hieradata/ => data/.

We should do this to the control-repo template new customers base off of
because in a Hiera 5 world, the global hiera.yaml should be very minimal
(possibly even ONLY having the console level), and everything else
(nodes, common) belongs in the environment hiera.yaml.

This control-repo template is how people start using Puppet. It should
reflect using our most modern technologies.

### CODE REVIEW

**Comment by trlinkin** [comment]
Seems good to me. I'll merge later on unless anyone disagrees. 👍

**Comment by natemccurdy** [comment]
Approved 👍

**Comment by beergeek** [comment]
Like it +1

**Comment by natemccurdy** [comment]
The future is now. I'm gonna merge this.

**Pull request merged**
