### PR TITLE
Topic/kingda/asdplng 47 review profile email

### PR DESCRIPTION
**Pull request by v1peractual**
This is adding the email profile in the default profile.

### CODE REVIEW

**Comment by binford2k** [comment]
Hi. Please see #95, and can your team audit & fix your remotes please?

**Comment by v1peractual** [comment]
I am sorry. I will work to fix it.

**Comment by reidmv** [comment]
@binford2k Github has a new feature these days, "Use This Template" rather than just cloning. Can we take advantage of that and update our docs for how to create a new control-repo using this repo as the template?

**Comment by binford2k** [comment]
@reidmv https://github.com/puppetlabs/control-repo/pull/100

**Pull request closed without merging**
