### PR TITLE
Move Gitlab instructions into separate file

### PR DESCRIPTION
**Pull request by petems**

### CODE REVIEW

**Comment by npwalker** [comment]
@petems I'm not necessarily opposed to a seperate file but what spurred you to want to move it to a second file?  The Readme is really short right now.

On a more salient point it appears as though you've taken the old instructions and put them in the seperate file which no longer apply to this repo as they include instructions for modifying hiera data with the pe_code_manager_webhook module.

**Comment by petems** [comment]
@npwalker Good point on the second part, I hadn't pulled from master when I started this. Which is also why I pulled it into a separate file, as it used to be way longer. I guess the main benefit is less merge conflict issues with having it in the README.md. What are the negatives?

**Comment by petems** [comment]
Ahhh, I see, we've completely moved all the more PE specific stuff out also. Ok, will need to rethink this.

**Comment by npwalker** [comment]
@petems please make your PR over on https://github.com/PuppetLabs-RampUpProgram/control-repo where all the PE specific stuff is staying around and I'll be adding to it

**Comment by petems** [comment]
@npwalker Yep, already done! :+1:

**Pull request closed without merging**
